-- Multi-city and campaign foundation, plus a unified admin view of account and guest runs.

create table if not exists public.cities (
  city_key text primary key,
  display_name text not null,
  province_name text,
  country_code text not null default 'CN',
  enabled boolean not null default false,
  is_default boolean not null default false,
  content_version text not null default 'v1',
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cities_key_format check (city_key ~ '^[a-z0-9][a-z0-9_-]{1,31}$')
);

create unique index if not exists cities_single_default_idx
  on public.cities (is_default)
  where is_default;

insert into public.cities (
  city_key,
  display_name,
  province_name,
  enabled,
  is_default,
  content_version,
  config
)
values (
  'hangzhou',
  '杭州浮生记',
  '浙江省',
  true,
  true,
  'hz-v1',
  jsonb_build_object(
    'scene_key', 'hangzhou',
    'product_catalog', 'hangzhou-v1',
    'location_catalog', 'hangzhou-v1',
    'theme_key', 'swiss-grid-v1'
  )
)
on conflict (city_key) do update set
  display_name = excluded.display_name,
  province_name = excluded.province_name,
  enabled = true,
  is_default = true,
  content_version = excluded.content_version,
  config = public.cities.config || excluded.config,
  updated_at = now();

create table if not exists public.city_route_rules (
  id bigint generated by default as identity primary key,
  city_key text not null references public.cities(city_key) on delete cascade,
  priority integer not null default 100,
  enabled boolean not null default true,
  country_codes text[] not null default array['CN']::text[],
  region_patterns text[] not null default '{}'::text[],
  city_patterns text[] not null default '{}'::text[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists city_route_rules_priority_idx
  on public.city_route_rules (enabled, priority, id);

create unique index if not exists city_route_rules_city_key_idx
  on public.city_route_rules (city_key);

insert into public.city_route_rules (
  city_key,
  priority,
  country_codes,
  region_patterns,
  city_patterns
)
select
  'hangzhou',
  10,
  array['CN'],
  array['zhejiang', '浙江'],
  array['hangzhou', '杭州']
where not exists (
  select 1 from public.city_route_rules where city_key = 'hangzhou'
);

alter table public.game_runs
  add column if not exists client_run_id text,
  add column if not exists session_id text,
  add column if not exists city_key text not null default 'hangzhou',
  add column if not exists city_version text not null default 'hz-v1',
  add column if not exists game_version text,
  add column if not exists share_code text,
  add column if not exists is_public boolean,
  add column if not exists published_at timestamptz;

update public.game_runs
set is_public = true,
    published_at = coalesce(published_at, created_at)
where is_public is null;

alter table public.game_runs
  alter column is_public set default false,
  alter column is_public set not null;

alter table public.guest_runs
  add column if not exists client_run_id text,
  add column if not exists session_id text,
  add column if not exists city_key text not null default 'hangzhou',
  add column if not exists city_version text not null default 'hz-v1',
  add column if not exists game_version text,
  add column if not exists share_code text,
  add column if not exists is_public boolean,
  add column if not exists published_at timestamptz;

-- Runs created before private archiving existed were intentionally submitted to the leaderboard.
update public.guest_runs
set is_public = true,
    published_at = coalesce(published_at, created_at)
where is_public is null;

alter table public.guest_runs
  alter column is_public set default false,
  alter column is_public set not null;

create unique index if not exists game_runs_client_run_id_idx
  on public.game_runs (client_run_id)
  where client_run_id is not null;

create unique index if not exists guest_runs_client_run_id_idx
  on public.guest_runs (client_run_id)
  where client_run_id is not null;

create unique index if not exists game_runs_share_code_idx
  on public.game_runs (share_code)
  where share_code is not null;

create unique index if not exists guest_runs_share_code_idx
  on public.guest_runs (share_code)
  where share_code is not null;

create index if not exists game_runs_city_created_idx
  on public.game_runs (city_key, created_at desc);

create index if not exists guest_runs_city_created_idx
  on public.guest_runs (city_key, created_at desc);

-- Raw guest snapshots and claim tokens must never be publicly readable.
drop policy if exists "Guest runs are publicly readable" on public.guest_runs;
drop policy if exists "Anonymous users can submit guest runs" on public.guest_runs;
create policy "Anonymous users can archive private guest runs"
  on public.guest_runs for insert
  with check (is_public = false and claimed_user_id is null);
revoke select on public.guest_runs from anon, authenticated;
revoke insert on public.guest_runs from anon, authenticated;

create or replace function public.archive_guest_run(p_payload jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_run_id uuid;
  v_client_run_id text := nullif(left(coalesce(p_payload->>'client_run_id', ''), 120), '');
  v_claim_token text := nullif(left(coalesce(p_payload->>'claim_token', ''), 120), '');
begin
  if v_client_run_id is null or v_claim_token is null then
    raise exception 'client_run_id and claim_token are required';
  end if;

  insert into public.guest_runs (
    guest_id,
    nickname,
    device_fingerprint,
    claim_token,
    score,
    cash,
    bank,
    debt,
    health,
    fame,
    coat,
    days_used,
    ended_reason,
    final_state,
    client_run_id,
    session_id,
    city_key,
    city_version,
    game_version,
    share_code,
    is_public
  ) values (
    left(coalesce(p_payload->>'guest_id', 'unknown'), 120),
    left(coalesce(nullif(trim(p_payload->>'nickname'), ''), '匿名玩家'), 24),
    left(coalesce(p_payload->>'device_fingerprint', ''), 160),
    v_claim_token,
    coalesce((p_payload->>'score')::integer, 0),
    coalesce((p_payload->>'cash')::integer, 0),
    coalesce((p_payload->>'bank')::integer, 0),
    coalesce((p_payload->>'debt')::integer, 0),
    coalesce((p_payload->>'health')::integer, 0),
    coalesce((p_payload->>'fame')::integer, 0),
    coalesce((p_payload->>'coat')::integer, 0),
    greatest(0, coalesce((p_payload->>'days_used')::integer, 0)),
    left(coalesce(p_payload->>'ended_reason', 'ended'), 40),
    coalesce(p_payload->'final_state', '{}'::jsonb),
    v_client_run_id,
    nullif(left(coalesce(p_payload->>'session_id', ''), 120), ''),
    left(coalesce(p_payload->>'city_key', 'hangzhou'), 32),
    left(coalesce(p_payload->>'city_version', 'hz-v1'), 80),
    nullif(left(coalesce(p_payload->>'game_version', ''), 120), ''),
    nullif(left(coalesce(p_payload->>'share_code', ''), 120), ''),
    false
  )
  on conflict (client_run_id) where client_run_id is not null
  do update set client_run_id = excluded.client_run_id
  returning id into v_run_id;

  return v_run_id;
end;
$$;

grant execute on function public.archive_guest_run(jsonb) to anon, authenticated;

create or replace view public.leaderboard as
select
  gr.user_id,
  coalesce(p.display_name, '匿名玩家') as display_name,
  p.avatar_url,
  gr.id as run_id,
  gr.score,
  gr.cash,
  gr.bank,
  gr.debt,
  gr.health,
  gr.days_used,
  gr.created_at,
  'account'::text as entry_type,
  null::text as claim_token
from public.game_runs gr
left join public.profiles p on p.id = gr.user_id
where gr.is_public

union all

select
  g.claimed_user_id as user_id,
  g.nickname as display_name,
  null::text as avatar_url,
  g.id as run_id,
  g.score,
  g.cash,
  g.bank,
  g.debt,
  g.health,
  g.days_used,
  g.created_at,
  'guest'::text as entry_type,
  null::text as claim_token
from public.guest_runs g
where g.is_public

order by score desc, created_at asc;

grant select on public.leaderboard to anon, authenticated;

create or replace function public.publish_account_run(p_run_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_run_id uuid;
begin
  update public.game_runs
  set is_public = true,
      published_at = coalesce(published_at, now())
  where id = p_run_id and user_id = auth.uid()
  returning id into v_run_id;

  if v_run_id is null then
    raise exception 'run not found';
  end if;
  return v_run_id;
end;
$$;

grant execute on function public.publish_account_run(uuid) to authenticated;

create or replace function public.publish_guest_run(
  p_claim_token text,
  p_nickname text
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_run_id uuid;
  v_nickname text;
begin
  v_nickname := left(trim(coalesce(p_nickname, '')), 24);
  if char_length(v_nickname) < 1 then
    raise exception 'nickname is required';
  end if;

  update public.guest_runs
  set nickname = v_nickname,
      is_public = true,
      published_at = coalesce(published_at, now())
  where claim_token = p_claim_token
  returning id into v_run_id;

  if v_run_id is null then
    raise exception 'run not found';
  end if;
  return v_run_id;
end;
$$;

grant execute on function public.publish_guest_run(text, text) to anon, authenticated;

create table if not exists public.campaigns (
  id uuid primary key default gen_random_uuid(),
  city_key text references public.cities(city_key) on delete set null,
  campaign_type text not null default 'sponsor_news',
  status text not null default 'draft',
  title text not null,
  body text not null,
  action_label text,
  action_url text,
  weight integer not null default 100,
  frequency_cap integer not null default 1,
  starts_at timestamptz,
  ends_at timestamptz,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint campaigns_type_check check (campaign_type in ('coupon', 'event', 'sponsor_news', 'sponsor_product')),
  constraint campaigns_status_check check (status in ('draft', 'active', 'paused', 'ended')),
  constraint campaigns_weight_check check (weight between 1 and 10000),
  constraint campaigns_frequency_cap_check check (frequency_cap between 1 and 50)
);

create index if not exists campaigns_delivery_idx
  on public.campaigns (status, city_key, starts_at, ends_at);

create table if not exists public.campaign_events (
  id bigint generated by default as identity primary key,
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  event_type text not null,
  city_key text not null default 'hangzhou',
  session_id text,
  client_run_id text,
  guest_id text,
  user_id uuid references auth.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint campaign_events_type_check check (event_type in ('eligible', 'impression', 'click', 'dismiss'))
);

create index if not exists campaign_events_campaign_created_idx
  on public.campaign_events (campaign_id, created_at desc);

create index if not exists campaign_events_session_created_idx
  on public.campaign_events (session_id, created_at desc);

alter table public.cities enable row level security;
alter table public.city_route_rules enable row level security;
alter table public.campaigns enable row level security;
alter table public.campaign_events enable row level security;

drop policy if exists "Enabled cities are publicly readable" on public.cities;
create policy "Enabled cities are publicly readable"
  on public.cities for select
  using (enabled);

drop policy if exists "Enabled city routes are publicly readable" on public.city_route_rules;
create policy "Enabled city routes are publicly readable"
  on public.city_route_rules for select
  using (enabled);

grant select on public.cities, public.city_route_rules to anon, authenticated;
revoke all on public.campaigns, public.campaign_events from anon, authenticated;

create or replace view public.active_campaigns
with (security_barrier = true)
as
select
  id,
  city_key,
  campaign_type,
  title,
  body,
  action_label,
  action_url,
  weight,
  frequency_cap,
  payload,
  starts_at,
  ends_at
from public.campaigns
where status = 'active'
  and (starts_at is null or starts_at <= now())
  and (ends_at is null or ends_at > now());

grant select on public.active_campaigns to anon, authenticated;

create or replace function public.resolve_city_by_hint(
  p_country text default null,
  p_region text default null,
  p_city text default null
)
returns table (
  city_key text,
  display_name text,
  content_version text,
  config jsonb,
  matched_by text
)
language sql
stable
security definer
set search_path = public
as $$
  with matched as (
    select
      c.city_key,
      c.display_name,
      c.content_version,
      c.config,
      case
        when coalesce(p_city, '') <> '' and exists (
          select 1 from unnest(r.city_patterns) pattern
          where lower(p_city) like '%' || lower(pattern) || '%'
        ) then 'city'
        when coalesce(p_region, '') <> '' and exists (
          select 1 from unnest(r.region_patterns) pattern
          where lower(p_region) like '%' || lower(pattern) || '%'
        ) then 'region'
        else 'country'
      end as matched_by,
      r.priority,
      case
        when coalesce(p_city, '') <> '' and exists (
          select 1 from unnest(r.city_patterns) pattern
          where lower(p_city) like '%' || lower(pattern) || '%'
        ) then 0
        when coalesce(p_region, '') <> '' and exists (
          select 1 from unnest(r.region_patterns) pattern
          where lower(p_region) like '%' || lower(pattern) || '%'
        ) then 1
        else 2
      end as match_rank
    from public.city_route_rules r
    join public.cities c on c.city_key = r.city_key
    where r.enabled and c.enabled
      and (
        coalesce(p_city, '') <> ''
        and exists (
          select 1 from unnest(r.city_patterns) pattern
          where lower(p_city) like '%' || lower(pattern) || '%'
        )
        or coalesce(p_region, '') <> ''
        and exists (
          select 1 from unnest(r.region_patterns) pattern
          where lower(p_region) like '%' || lower(pattern) || '%'
        )
        or coalesce(p_country, '') <> ''
        and upper(p_country) = any(r.country_codes)
      )
    order by match_rank asc, r.priority asc, r.id asc
    limit 1
  )
  select city_key, display_name, content_version, config, matched_by from matched
  union all
  select c.city_key, c.display_name, c.content_version, c.config, 'default'
  from public.cities c
  where c.enabled and c.is_default and not exists (select 1 from matched)
  limit 1;
$$;

grant execute on function public.resolve_city_by_hint(text, text, text) to anon, authenticated;

create or replace function public.record_campaign_event(
  p_campaign_id uuid,
  p_event_type text,
  p_city_key text default 'hangzhou',
  p_session_id text default null,
  p_client_run_id text default null,
  p_guest_id text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  if p_event_type not in ('eligible', 'impression', 'click', 'dismiss') then
    raise exception 'invalid campaign event type';
  end if;

  if not exists (
    select 1 from public.active_campaigns ac where ac.id = p_campaign_id
  ) then
    raise exception 'campaign is not active';
  end if;

  insert into public.campaign_events (
    campaign_id,
    event_type,
    city_key,
    session_id,
    client_run_id,
    guest_id,
    user_id,
    metadata
  ) values (
    p_campaign_id,
    p_event_type,
    coalesce(nullif(p_city_key, ''), 'hangzhou'),
    nullif(left(coalesce(p_session_id, ''), 120), ''),
    nullif(left(coalesce(p_client_run_id, ''), 120), ''),
    nullif(left(coalesce(p_guest_id, ''), 120), ''),
    auth.uid(),
    coalesce(p_metadata, '{}'::jsonb)
  )
  returning id into v_id;

  return v_id;
end;
$$;

grant execute on function public.record_campaign_event(uuid, text, text, text, text, text, jsonb)
  to anon, authenticated;

create or replace function public.admin_overview()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select case
    when not public.is_admin() then
      jsonb_build_object('error', 'forbidden')
    else
      jsonb_build_object(
        'users', (select count(*) from auth.users),
        'profiles', (select count(*) from public.profiles),
        'account_runs', (select count(*) from public.game_runs),
        'guest_runs', (select count(*) from public.guest_runs),
        'game_runs', (
          (select count(*) from public.game_runs)
          + (select count(*) from public.guest_runs)
        ),
        'players_with_runs', (
          (select count(distinct user_id) from public.game_runs)
          + (select count(distinct guest_id) from public.guest_runs where claimed_user_id is null)
        ),
        'events', (
          (select count(*) from public.game_events)
          + (select coalesce(sum(
              case when jsonb_typeof(final_state->'events') = 'array'
                then jsonb_array_length(final_state->'events') else 0 end
            ), 0) from public.guest_runs)
        ),
        'best_score', (
          select coalesce(max(score), 0) from (
            select score from public.game_runs
            union all
            select score from public.guest_runs
          ) scores
        ),
        'avg_score', (
          select coalesce(round(avg(score))::integer, 0) from (
            select score from public.game_runs
            union all
            select score from public.guest_runs
          ) scores
        ),
        'runs_today', (
          select count(*) from (
            select created_at from public.game_runs
            union all
            select created_at from public.guest_runs
          ) runs where created_at >= date_trunc('day', now())
        ),
        'cities', (select count(*) from public.cities),
        'active_campaigns', (select count(*) from public.active_campaigns),
        'campaign_impressions', (
          select count(*) from public.campaign_events where event_type = 'impression'
        ),
        'campaign_clicks', (
          select count(*) from public.campaign_events where event_type = 'click'
        )
      )
  end;
$$;

create or replace function public.admin_players_v2()
returns table (
  player_key text,
  source text,
  email text,
  display_name text,
  created_at timestamptz,
  last_seen_at timestamptz,
  run_count bigint,
  best_score integer
)
language sql
stable
security definer
set search_path = public
as $$
  select * from (
    select
      'account:' || u.id::text as player_key,
      'account'::text as source,
      u.email,
      coalesce(p.display_name, split_part(u.email, '@', 1), '匿名玩家') as display_name,
      u.created_at,
      greatest(u.last_sign_in_at, max(gr.created_at)) as last_seen_at,
      count(gr.id) as run_count,
      coalesce(max(gr.score), 0)::integer as best_score
    from auth.users u
    left join public.profiles p on p.id = u.id
    left join public.game_runs gr on gr.user_id = u.id
    where public.is_admin()
    group by u.id, p.display_name

    union all

    select
      'guest:' || g.guest_id as player_key,
      'guest'::text as source,
      null::text as email,
      max(g.nickname) as display_name,
      min(g.created_at) as created_at,
      max(g.created_at) as last_seen_at,
      count(*) as run_count,
      max(g.score)::integer as best_score
    from public.guest_runs g
    where public.is_admin() and g.claimed_user_id is null
    group by g.guest_id
  ) players
  order by last_seen_at desc nulls last
  limit 500;
$$;

create or replace function public.admin_runs_v2()
returns table (
  run_key text,
  id uuid,
  source text,
  user_id uuid,
  email text,
  display_name text,
  city_key text,
  city_version text,
  game_version text,
  score integer,
  cash integer,
  bank integer,
  debt integer,
  health integer,
  fame integer,
  days_used integer,
  ended_reason text,
  event_count bigint,
  final_state jsonb,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select * from (
    select
      'account:' || gr.id::text as run_key,
      gr.id,
      'account'::text as source,
      gr.user_id,
      u.email,
      coalesce(p.display_name, split_part(u.email, '@', 1), '匿名玩家') as display_name,
      gr.city_key,
      gr.city_version,
      gr.game_version,
      gr.score,
      gr.cash,
      gr.bank,
      gr.debt,
      gr.health,
      gr.fame,
      gr.days_used,
      gr.ended_reason,
      count(ge.id) as event_count,
      gr.final_state,
      gr.created_at
    from public.game_runs gr
    join auth.users u on u.id = gr.user_id
    left join public.profiles p on p.id = gr.user_id
    left join public.game_events ge on ge.run_id = gr.id
    where public.is_admin()
    group by gr.id, u.email, p.display_name

    union all

    select
      'guest:' || g.id::text as run_key,
      g.id,
      'guest'::text as source,
      g.claimed_user_id as user_id,
      null::text as email,
      g.nickname as display_name,
      g.city_key,
      g.city_version,
      g.game_version,
      g.score,
      g.cash,
      g.bank,
      g.debt,
      g.health,
      g.fame,
      g.days_used,
      g.ended_reason,
      case when jsonb_typeof(g.final_state->'events') = 'array'
        then jsonb_array_length(g.final_state->'events') else 0 end::bigint as event_count,
      g.final_state,
      g.created_at
    from public.guest_runs g
    where public.is_admin()
  ) runs
  order by created_at desc
  limit 500;
$$;

create or replace function public.admin_events_v2(p_run_key text)
returns table (
  id text,
  run_key text,
  source text,
  user_id uuid,
  event_index integer,
  event_type text,
  day integer,
  message text,
  state jsonb,
  payload jsonb,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select * from (
    select
      ge.id::text as id,
      'account:' || ge.run_id::text as run_key,
      'account'::text as source,
      ge.user_id,
      ge.event_index,
      ge.event_type,
      ge.day,
      ge.message,
      ge.state,
      ge.payload,
      ge.created_at
    from public.game_events ge
    where public.is_admin()
      and p_run_key = 'account:' || ge.run_id::text

    union all

    select
      'guest-event:' || g.id::text || ':' || (e.ordinality - 1)::text as id,
      'guest:' || g.id::text as run_key,
      'guest'::text as source,
      g.claimed_user_id as user_id,
      case when coalesce(e.value->>'event_index', '') ~ '^\d+$'
        then (e.value->>'event_index')::integer else (e.ordinality - 1)::integer end as event_index,
      coalesce(nullif(e.value->>'event_type', ''), 'log') as event_type,
      case when coalesce(e.value->>'day', '') ~ '^\d+$'
        then (e.value->>'day')::integer else 0 end as day,
      left(coalesce(e.value->>'message', ''), 240) as message,
      case when jsonb_typeof(e.value->'state') = 'object' then e.value->'state' else '{}'::jsonb end as state,
      case when jsonb_typeof(e.value->'payload') = 'object' then e.value->'payload' else '{}'::jsonb end as payload,
      g.created_at
    from public.guest_runs g
    cross join lateral jsonb_array_elements(
      case when jsonb_typeof(g.final_state->'events') = 'array'
        then g.final_state->'events' else '[]'::jsonb end
    ) with ordinality as e(value, ordinality)
    where public.is_admin()
      and p_run_key = 'guest:' || g.id::text
  ) events
  order by event_index asc
  limit 2000;
$$;

create or replace function public.admin_event_summary_v2()
returns table (
  event_type text,
  event_count bigint,
  player_count bigint,
  run_count bigint,
  last_seen_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  with all_events as (
    select
      ge.event_type,
      'account:' || ge.user_id::text as player_key,
      'account:' || ge.run_id::text as run_key,
      ge.created_at
    from public.game_events ge
    where public.is_admin()

    union all

    select
      coalesce(nullif(e.value->>'event_type', ''), 'log') as event_type,
      'guest:' || g.guest_id as player_key,
      'guest:' || g.id::text as run_key,
      g.created_at
    from public.guest_runs g
    cross join lateral jsonb_array_elements(
      case when jsonb_typeof(g.final_state->'events') = 'array'
        then g.final_state->'events' else '[]'::jsonb end
    ) as e(value)
    where public.is_admin()
  )
  select
    event_type,
    count(*) as event_count,
    count(distinct player_key) as player_count,
    count(distinct run_key) as run_count,
    max(created_at) as last_seen_at
  from all_events
  group by event_type
  order by event_count desc, event_type asc;
$$;

create or replace function public.admin_cities()
returns table (
  city_key text,
  display_name text,
  province_name text,
  country_code text,
  enabled boolean,
  is_default boolean,
  content_version text,
  config jsonb,
  created_at timestamptz,
  updated_at timestamptz,
  priority integer,
  country_codes text[],
  region_patterns text[],
  city_patterns text[]
)
language sql
stable
security definer
set search_path = public
as $$
  select
    c.city_key,
    c.display_name,
    c.province_name,
    c.country_code,
    c.enabled,
    c.is_default,
    c.content_version,
    c.config,
    c.created_at,
    c.updated_at,
    coalesce(r.priority, 100),
    coalesce(r.country_codes, array['CN']::text[]),
    coalesce(r.region_patterns, '{}'::text[]),
    coalesce(r.city_patterns, '{}'::text[])
  from public.cities c
  left join public.city_route_rules r on r.city_key = c.city_key
  where public.is_admin()
  order by c.is_default desc, c.display_name;
$$;

create or replace function public.admin_campaigns()
returns setof public.campaigns
language sql
stable
security definer
set search_path = public
as $$
  select c.* from public.campaigns c where public.is_admin() order by c.created_at desc;
$$;

create or replace function public.admin_campaign_events(p_campaign_id uuid default null)
returns setof public.campaign_events
language sql
stable
security definer
set search_path = public
as $$
  select ce.*
  from public.campaign_events ce
  where public.is_admin()
    and (p_campaign_id is null or ce.campaign_id = p_campaign_id)
  order by ce.created_at desc
  limit 2000;
$$;

create or replace function public.admin_upsert_city(
  p_city_key text,
  p_display_name text,
  p_enabled boolean,
  p_is_default boolean,
  p_content_version text,
  p_config jsonb,
  p_country_codes text[] default array['CN']::text[],
  p_region_patterns text[] default '{}'::text[],
  p_city_patterns text[] default '{}'::text[],
  p_priority integer default 100
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_key text := lower(trim(coalesce(p_city_key, '')));
begin
  if not public.is_admin() then raise exception 'forbidden'; end if;
  if v_key !~ '^[a-z0-9][a-z0-9_-]{1,31}$' then raise exception 'invalid city key'; end if;
  if trim(coalesce(p_display_name, '')) = '' then raise exception 'display name is required'; end if;

  if p_is_default then update public.cities set is_default = false where is_default; end if;
  insert into public.cities (
    city_key, display_name, enabled, is_default, content_version, config, updated_at
  ) values (
    v_key,
    left(trim(p_display_name), 80),
    coalesce(p_enabled, false),
    coalesce(p_is_default, false),
    left(coalesce(nullif(trim(p_content_version), ''), 'v1'), 80),
    coalesce(p_config, '{}'::jsonb),
    now()
  )
  on conflict (city_key) do update set
    display_name = excluded.display_name,
    enabled = excluded.enabled,
    is_default = excluded.is_default,
    content_version = excluded.content_version,
    config = excluded.config,
    updated_at = now();

  insert into public.city_route_rules (
    city_key, priority, enabled, country_codes, region_patterns, city_patterns, updated_at
  ) values (
    v_key,
    greatest(1, coalesce(p_priority, 100)),
    coalesce(p_enabled, false),
    coalesce(p_country_codes, array['CN']::text[]),
    coalesce(p_region_patterns, '{}'::text[]),
    coalesce(p_city_patterns, '{}'::text[]),
    now()
  )
  on conflict (city_key) do update set
    priority = excluded.priority,
    enabled = excluded.enabled,
    country_codes = excluded.country_codes,
    region_patterns = excluded.region_patterns,
    city_patterns = excluded.city_patterns,
    updated_at = now();

  return v_key;
end;
$$;

create or replace function public.admin_upsert_campaign(
  p_id uuid,
  p_city_key text,
  p_campaign_type text,
  p_status text,
  p_title text,
  p_body text,
  p_action_label text,
  p_action_url text,
  p_weight integer,
  p_frequency_cap integer,
  p_starts_at timestamptz,
  p_ends_at timestamptz,
  p_payload jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid := coalesce(p_id, gen_random_uuid());
begin
  if not public.is_admin() then raise exception 'forbidden'; end if;
  insert into public.campaigns (
    id, city_key, campaign_type, status, title, body, action_label, action_url,
    weight, frequency_cap, starts_at, ends_at, payload, updated_at
  ) values (
    v_id,
    nullif(trim(coalesce(p_city_key, '')), ''),
    p_campaign_type,
    p_status,
    left(trim(p_title), 120),
    left(trim(p_body), 1200),
    nullif(left(trim(coalesce(p_action_label, '')), 80), ''),
    nullif(left(trim(coalesce(p_action_url, '')), 600), ''),
    p_weight,
    p_frequency_cap,
    p_starts_at,
    p_ends_at,
    coalesce(p_payload, '{}'::jsonb),
    now()
  )
  on conflict (id) do update set
    city_key = excluded.city_key,
    campaign_type = excluded.campaign_type,
    status = excluded.status,
    title = excluded.title,
    body = excluded.body,
    action_label = excluded.action_label,
    action_url = excluded.action_url,
    weight = excluded.weight,
    frequency_cap = excluded.frequency_cap,
    starts_at = excluded.starts_at,
    ends_at = excluded.ends_at,
    payload = excluded.payload,
    updated_at = now();
  return v_id;
end;
$$;

create or replace function public.admin_set_campaign_status(p_id uuid, p_status text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'forbidden'; end if;
  update public.campaigns set status = p_status, updated_at = now() where id = p_id;
  return found;
end;
$$;

grant execute on function public.admin_overview() to authenticated;
grant execute on function public.admin_players_v2() to authenticated;
grant execute on function public.admin_runs_v2() to authenticated;
grant execute on function public.admin_events_v2(text) to authenticated;
grant execute on function public.admin_event_summary_v2() to authenticated;
grant execute on function public.admin_cities() to authenticated;
grant execute on function public.admin_campaigns() to authenticated;
grant execute on function public.admin_campaign_events(uuid) to authenticated;
grant execute on function public.admin_upsert_city(text, text, boolean, boolean, text, jsonb, text[], text[], text[], integer) to authenticated;
grant execute on function public.admin_upsert_campaign(uuid, text, text, text, text, text, text, text, integer, integer, timestamptz, timestamptz, jsonb) to authenticated;
grant execute on function public.admin_set_campaign_status(uuid, text) to authenticated;
